name: 'Cortx PR checklist'
author: Venkatesh K
description: 'Cortx PR checklist'

runs:
  using: "composite"
  steps:
    - run: python -m pip install PyGithub  # Installing dependencies
      shell: bash
    - run: python ${{ github.action_path }}/main-script.py ${{ inputs.gh_token }} ${{ inputs.file_name }} ${{ github.workspace }} ${{ inputs.max_repo_description }}
      shell: bash

inputs:
  REPO:
    description: "The path to the repository where the action will be used, e.g. 'venkuppu-chn/pr-checklist' (automatically set)"
    required: true
    default: ${{ github.repository }}
  TOKEN:
    description: "The GitHub access token to allow us to retrieve, create and update issues (automatically set)"
    required: false
    default: ${{ github.token }}
    
